### PR TITLE
Fix build errors and tests

### PR DESCRIPTION
**Pull request by hgy59**
Got this working again
see  [travis build status](https://travis-ci.org/hgy59/spkrepo/builds)

- Includes the fixes and DSM 6 enhancements of PR #8  (resource and privilege in VersionModel, incl. db migrate script)
- `test_anonymous` redirects to the login page (status 302 instead of 403)
- `test_anonymous_redirects_to_login` added to validate the redirection
- flask-admin does not run with newer sqlalchemy versions
- removed custom flask-login of @Diaoul (not needed and not available anymore)
- flask module import naming updated
- `config.py` security needs password hash and salt
- travis config updated (no need to install sqlite3)
- for an unknown reason the `info_stream = io.BytesIO('\n'.join(['%s="%s"' % (k, v) for k, v in info.items()]).encode(info_encoding))` fails with `UnicodeDecodeError: 'ascii' codec can't decode byte...`, but runs if the info is assigend to a variable first.

Added a small ajustment to not remove the data folder with `manage.py clean` since I am working on a docker configuration with shared volume for the data folder.

This work was a kind of sofisticated, since the dependencies of Flask are really complex. I did not succeed to use any newer version of Flask-Admin.

### CODE REVIEW

**Comment by hgy59** [comment]
db migration script updated to include migration of screenshot path column (see 2af5e5f of @ymartin59 )

**Comment by hgy59** [comment]
This is ready to merge. 
Working on Dockerfile on a different branch, that is based on this changes

**Comment by ymartin59** [comment]
@Diaoul Why not move "spkrepo" project under SynoCommunity?

**Comment by Diaoul** [comment]
It actually started as a SynoCommunity project but I was the only one working on it and it made things easier to manage like that, permission-wise.
I'll transfer it.

**Comment by Diaoul** [comment]
Done

**Comment by ymartin59** [comment]
Just a question: I do not understand what columns "version.privilege" and "version.resource" are for in database. What are expected use cases?

**Pull request merged**
