### PR TITLE
Fixes + DSM6 support

### PR DESCRIPTION
**Pull request by Dr-Bean**
Various fixes to get the tests to run succesfully, and add support for DSM6-related changes to package management.

### CODE REVIEW

**Comment by Dr-Bean** [comment]
I assumed that the formatting of `privilege` and `resource` was the same as for PKG_DEPS...it's not.
Besides, I left one line in utils.py which shouldn't be there, causing an upload to fail. I'll come back to this once again...

**Comment by Dr-Bean** [comment]
Upload works (locally anyway). The one failing test (`test_anonymous`) on Travis occurs locally too, not sure what the reason is to get a 302 instead of a 403.

@Diaoul, your flask-login fork is no longer available, hence the change in `requirements.txt` with https://github.com/Diaoul/spkrepo/pull/8/commits/2ffe8381b326150de33e6cd5ed49400664db2764. Travis wouldn't run otherwise. Was the issue fixed upstream, or did you set the fork to private or something?

**Comment by Dr-Bean** [comment]
ping @Diaoul. I realize you're probably busy with other things, but merging and publishing this allows us to move forward with DSM6 stuff. Thanks :)

**Comment by Diaoul** [comment]
Yes I just moved so quite busy indeed. Publishing this will probably break the server and I need to be available to make appropriate fixes this is why I didn't publish it yet. I'll let you know when I can do that, probably in a week or so.

**Comment by Dr-Bean** [comment]
Hope the new place is nice :) Take your time...that's coming from someone who's still surrounded by unemptied moving boxes :/

**Comment by m4tt075** [comment]
@diaoul Is this still being worked on or abandonded for good? Both is perfectly fine of course, but I'm asking to understand whether we can continue using Synocommunity as publication platform or whether we should better be looking for alternatives moving forward. Any insights appreciated.

**Comment by Safihre** [comment]
Ping @DiaouI, I also wonder if this is ever going to be finished and merged?
Thanks! :+1:

**Comment by MatthiasLohr** [comment]
Any update here?

**Comment by m4tt075** [comment]
This is obsolete. @ymartin59 fixed it. We have been publishing 6.1 packages for many months already. The repo is perfectly fine. The problem was that certain packages needed to be updated to support 6.1 and beyond too. If you are interested in details and the list of packages that still need to be tackled, please take a look here: https://github.com/SynoCommunity/spksrc/issues/2904.

**Comment by ymartin59** [comment]
In fact changes here are interesting even if not mandatory for DSM 6 package to be published. And have been merged into master - this PR is left opened as a reminder that it has not been published yet in production - refactoring to Docker container is expected...

**Pull request closed without merging**
